#!/usr/bin/env bash

if [ -d ~/boxbox ]; then
  echo "[!] ~/boxbox directory exists"
  echo "[!] Box Box is already installed"
  echo "[!] Please remove it before you try to install it again"
  exit 1
fi

# -------------------------------------------------------------------------------------------------------------------------

echo "[*] Checking if git is installed"

if ! (which git > /dev/null); then
  echo "[!] Please install git"
fi

# -------------------------------------------------------------------------------------------------------------------------

echo "[*] Checking if wget is installed"

if ! (which wget > /dev/null); then
  echo "[!] Please install wget"
fi

# -------------------------------------------------------------------------------------------------------------------------

echo "[*] Checking if Virtual Box is available"

if which vboxmanage > /dev/null; then
  version=$(vboxmanage --version)

  echo "[*] Virtual Box found: $version"

  if ! [[ "$version" =~ "5.0" ]]; then
    echo "[!] Expected Virtual Box version 5"
    exit 1
  fi
else
  echo "[*] Installing Virtual Box version 5"

  wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -

  sudo apt-get update
  sudo apt-get install -y virtualbox-5.0
fi

# -------------------------------------------------------------------------------------------------------------------------

echo "[*] Checking if Vagrant is available"

if which vagrant> /dev/null; then
  version=$(vagrant --version)

  echo "[*] Vagrant found: $version"

  if ! [[ "$version" =~ "1.8" ]]; then
    echo "[!] Expected Vagrant version 1.8"
    exit 1
  fi
else
  echo "[*] Installing Vagrant"

  wget https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb -o /tmp/vagrant_1.8.1_x86_64.deb

  sudo dpkg -i /tmp/vagrant_1.8.1_x86_64.deb
fi

# -------------------------------------------------------------------------------------------------------------------------

echo "[*] Installing vagrant hostmanager"

vagrant plugin install vagrant-hostmanager

# -------------------------------------------------------------------------------------------------------------------------

echo "[*] Cloning boxbox from GitHub"

git clone https://github.com/shiroyasha/boxbox.git ~/boxbox
cd ~/boxbox

echo "[*] Provisioning your boxbox"
vagrant up

echo "[*] Setting up aliases in bash_profile"
echo 'alias bb="cd ~/boxbox && vagrant up && vagrant ssh -c \"tmux -2\""' >> ~/.bash_profile
echo 'alias bhalt="cd ~/boxbox && vagrant halt' >> ~/.bash_profile >> ~/.bash_profile

echo "[*] Done"
echo ""
echo "Type 'bb' to start using your boxbox machine"
